ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE}

ARG COMPILER=gcc
ARG COMPILER_VERSION=12
ARG BUILD_TYPE=Release

RUN apt-get update -qq && export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y --no-install-recommends \
    python3.10 python3-pip python3.10-venv \
    ${COMPILER}-${COMPILER_VERSION} \
    ${COMPILER}-${COMPILER_VERSION}
RUN if [ "$COMPILER" = "gcc" ]; then apt-get install -y --no-install-recommends g++-${COMPILER_VERSION}; fi

ENV CC=${COMPILER}-${COMPILER_VERSION}
ENV CXX=${COMPILER}-${COMPILER_VERSION}
ENV CONAN_REVISIONS_ENABLED=1
ENV CONAN_USER_HOME=/teiacare_sdk

WORKDIR /teiacare_sdk
COPY . .
RUN python3 -m venv .venv
RUN . /teiacare_sdk/.venv/bin/activate
RUN python3 -m pip install -r scripts/requirements.txt --no-cache-dir --disable-pip-version-check

RUN python3 scripts/conan/setup.py ${BUILD_TYPE} ${COMPILER} ${COMPILER_VERSION}
