function(setup_packages COMPILER_NAME_C COMPILER_VERSION_MAJOR CONANFILE_DIRECTORY)	
	set(ENV{CC} "${COMPILER_NAME_C}-${COMPILER_VERSION_MAJOR}")
	set(ENV{CXX} "${COMPILER_NAME_CXX}-${COMPILER_VERSION_MAJOR}")
	find_package(Python COMPONENTS Interpreter REQUIRED)
	execute_process(
		COMMAND ${Python_EXECUTABLE}
		scripts/conan/profile.py ${COMPILER_NAME_C} ${COMPILER_VERSION_MAJOR}
		WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
	)
	execute_process(
		COMMAND ${Python_EXECUTABLE}
		scripts/conan/install.py ${CMAKE_BUILD_TYPE} ${COMPILER_NAME_C}${COMPILER_VERSION_MAJOR} "-d" ${CONANFILE_DIRECTORY}
		WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
	)
endfunction()
