name: CI Linux

on:
  workflow_dispatch:
  pull_request: 
  push:

jobs:
  build:
    runs-on: ${{matrix.OS}}
    name: '${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}} - ${{matrix.BUILD_TYPE}}'
    strategy:
      fail-fast: false
      matrix:
        BUILD_TYPE: [Debug, Release, RelWithDebInfo]
        COMPILER: [gcc, clang]
        OS: [ubuntu-22.04]
        include:
         - COMPILER: gcc
           COMPILER_VERSION: 12
         - COMPILER: clang
           COMPILER_VERSION: 15

    env:
      CONAN_USER_HOME: ${{github.workspace}}
      ACTIVATE_VIRTUAL_ENV: 'source .venv/bin/activate'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        shell: bash
        run: |
          python -m venv .venv
          ${{env.ACTIVATE_VIRTUAL_ENV}}
          pip install -r scripts/requirements.txt
          python scripts/conan/setup.py ${{matrix.BUILD_TYPE}} ${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}}

      - name: Build Library
        shell: bash
        run: |
          ${{env.ACTIVATE_VIRTUAL_ENV}}
          python scripts/cmake/configure.py ${{matrix.BUILD_TYPE}} ${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}} --warnings
          python scripts/cmake/build.py ${{matrix.BUILD_TYPE}}
          python scripts/cmake/install.py ${{matrix.BUILD_TYPE}}

      - name: Build Examples
        shell: bash
        run: |
          ${{env.ACTIVATE_VIRTUAL_ENV}}
          python scripts/cmake/configure.py ${{matrix.BUILD_TYPE}} ${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}} --warnings --examples
          python scripts/cmake/build.py ${{matrix.BUILD_TYPE}}
          python scripts/cmake/install.py ${{matrix.BUILD_TYPE}}

      - name: Run Examples
        shell: bash
        run: |
          ${{env.ACTIVATE_VIRTUAL_ENV}}
          python scripts/tools/run_examples.py install/examples

      - name: Build Unit Tests
        shell: bash
        run: |
          ${{env.ACTIVATE_VIRTUAL_ENV}}
          python scripts/cmake/configure.py ${{matrix.BUILD_TYPE}} ${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}} --warnings --unit_tests
          python scripts/cmake/build.py ${{matrix.BUILD_TYPE}}
          python scripts/cmake/install.py ${{matrix.BUILD_TYPE}}

      - name: Run Unit Tests
        continue-on-error: true
        shell: bash
        run: |
          ${{env.ACTIVATE_VIRTUAL_ENV}}
          python scripts/tools/run_unit_tests.py ${{matrix.BUILD_TYPE}}

      - name: Upload Unit Tests Results
        uses: actions/upload-artifact@v4
        with:
          name: 'Unit Tests - ${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}} - ${{matrix.BUILD_TYPE}}'
          path: 'results/unit_tests/unit_tests.xml'

  publish-test-results:
    name: 'Publish Unit Tests Results'
    needs: build
    runs-on: ubuntu-22.04
    if: always()
    permissions:
      checks: write
      pull-requests: write
      
    steps:
      - name: Download Unit Tests Results
        uses: actions/download-artifact@v4
        with:
          path: 'unit_test_reports'

      - name: Publish Unit Tests Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "unit_test_reports/**/*.xml"
          
