name: CI Windows

on:
  workflow_dispatch:
  pull_request: 
  #  branches:
  #    - 'develop'
  #    - 'feature/*'
  #    - 'release/*'
  #    - 'hotfix/*'
  #  tags:
  #    - 'v*'
  push:
  #  branches:
  #    - 'develop'
  #    - 'feature/*'
  #    - 'release/*'
  #    - 'hotfix/*'
  #  tags:
  #    - 'v*'

jobs:
  build:
    runs-on: ${{matrix.OS}}
    name: '${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}} - ${{matrix.BUILD_TYPE}}'
    strategy:
      fail-fast: false
      matrix:
        BUILD_TYPE: [Debug, Release]
        COMPILER: [visual_studio]
        OS: [windows-2019, windows-2022]
        include:
         - COMPILER: visual_studio
           COMPILER_VERSION: 16
           OS: 'windows-2019'
           SETUP_BUILD_ENV: 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'
         - COMPILER: visual_studio
           COMPILER_VERSION: 17
           OS: 'windows-2022'
           SETUP_BUILD_ENV: 'call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'
  
    env:
      CONAN_USER_HOME: ${{github.workspace}}
      ACTIVATE_VIRTUAL_ENV: 'call ".venv\Scripts\activate.bat"'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        shell: cmd
        run: |
          python -m venv .venv
          ${{matrix.ACTIVATE_VIRTUAL_ENV}}
          pip install -r scripts/requirements.txt
          python scripts/conan/setup.py ${{matrix.BUILD_TYPE}} ${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}}

      - name: Build Library
        shell: cmd
        run: |
          ${{env.ACTIVATE_VIRTUAL_ENV}}
          ${{matrix.SETUP_BUILD_ENV}}
          python scripts/cmake/configure.py ${{matrix.BUILD_TYPE}} ${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}}
          python scripts/cmake/build.py ${{matrix.BUILD_TYPE}}
          python scripts/cmake/install.py ${{matrix.BUILD_TYPE}}

      - name: Build Examples
        shell: cmd
        run: |
          ${{env.ACTIVATE_VIRTUAL_ENV}}
          ${{matrix.SETUP_BUILD_ENV}}
          python scripts/cmake/configure.py ${{matrix.BUILD_TYPE}} ${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}} --examples
          python scripts/cmake/build.py ${{matrix.BUILD_TYPE}}
          python scripts/cmake/install.py ${{matrix.BUILD_TYPE}}

      - name: Run Examples
        shell: cmd
        run: |
          ${{env.ACTIVATE_VIRTUAL_ENV}}
          ${{matrix.SETUP_BUILD_ENV}}
          python scripts/tools/run_examples.py install/examples

      - name: Build Unit Tests
        shell: cmd
        run: |
          ${{env.ACTIVATE_VIRTUAL_ENV}}
          ${{matrix.SETUP_BUILD_ENV}}
          python scripts/cmake/configure.py ${{matrix.BUILD_TYPE}} ${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}} --unit_tests
          python scripts/cmake/build.py ${{matrix.BUILD_TYPE}}
          python scripts/cmake/install.py ${{matrix.BUILD_TYPE}}

      - name: Run Unit Tests
        continue-on-error: true
        shell: cmd
        run: |
          ${{env.ACTIVATE_VIRTUAL_ENV}}
          ${{matrix.SETUP_BUILD_ENV}}
          python scripts/tools/run_unit_tests.py ${{matrix.BUILD_TYPE}}

      - name: Upload Unit Tests Results
        uses: actions/upload-artifact@v4
        with:
          name: 'Unit Tests - ${{matrix.COMPILER}} ${{matrix.COMPILER_VERSION}} - ${{matrix.BUILD_TYPE}}'
          path: 'results/unit_tests/unit_tests.xml'

  publish-test-results:
    name: 'Publish Unit Tests Results'
    needs: build
    runs-on: ubuntu-22.04
    if: always()
    permissions:
      checks: write
      pull-requests: write
      
    steps:
      - name: Download Unit Tests Results
        uses: actions/download-artifact@v4
        with:
          path: 'unit_test_reports'

      - name: Publish Unit Tests Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "unit_test_reports/**/*.xml"

